travis:
  secure:
    BINSTAR_TOKEN: LIDeg82LjMJL14eNFP11lTfc52SycY4gG+NALeU9h6oyeoCOSZeyPpFfYlKHwS1wPL+Q74CPbZs/A4C7t9zUZTDySkxuVq5XCFcG2Go05Oc5layCaq5YZnd3unXZDpJ9rQ/YSg9pq1GGGCjFrqoOBmjxJbit2qvVUB+m1rEp0VtcpMVcTd84wh8YzYVCJ5GM8sqa15uoJChuif4EvCywDctipItIYITApKNdtEtnaAd0foPztHbwudQdg23Bhii8J7azDzYN382vWxTI8vxlzQ0KfTLJPnCbGkKJ9O5ASt1rWuFw3b0tK7B4qGkfQhE10uMFHnXdKaceE1CEqEr+p5n2XZu5BNl17gdSllJeaEke149U5X4nw5Z9Qe2D2hdr0mvkw4SupeRth2vJ7OQypeeYeCYYrMA6bXIEZeeZZA+GHN+h2clR1LdINFbDV9/ZoJShQuKUnDHLxAonTFLvwdpcfVHjy+sobgaULx0k4iE+c9n4DMWNX/76jW6Dq5UCAGxN1z2UEAdN1f3wiRf5fk+455a/KLkPE1mvA6CUQyeyfvXN4cwfqtnersIMaDdiCHH687KYpmIt5kbptqEZIsaQa2+RRRAMRK0X8uK7N6hR0/SPVS2tPbasGXEMKOg+vL+cOdEaYfawp5YBjEsQTLFP3Hq8oDXutI4P9r1tyjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
